import { state, navigate } from './state.js';
import { api } from './api.js';
import { root, escapeHtml, statusLabel, navigation, showToast, openModal, closeModal } from './ui.js';

const render = () => { views[state.view](); document.querySelectorAll('[data-go]').forEach((b) => { b.onclick = () => { navigate(b.dataset.go); render(); }; }); };
const home = () => { root.innerHTML = `<div class="shell">${navigation()}<section class="hero"><div><div class="eyebrow">Laptop repair, simplified</div><h1>Repair updates<br>without the<br>phone tag.</h1><p>Give your team a calm, focused workspace and give customers clear answers whenever they need them.</p><button class="primary" data-go="lookup">Check a repair status →</button></div><div class="preview"><div class="preview-head"><span>YOUR REPAIRS</span><span>3 active</span></div>${state.tickets.map((t) => `<div class="mini-card"><div>${escapeHtml(t.customer_name)} <span class="pill">${statusLabel(t.status).toUpperCase()}</span></div><small>${escapeHtml(t.device_info)}</small></div>`).join('')}</div></section></div>`; };
const login = () => { root.innerHTML = `<div class="screen shell">${navigation('tech')}<section class="login-wrap"><div class="auth-card"><div class="brand"><span class="brand-mark">✦</span>FixFlow</div><h1>Welcome back</h1><p>Sign in to manage your repair tickets.</p><form id="login-form"><div class="field"><label>Email</label><input required type="email" value="tech@fixflow.test"></div><div class="field"><label>Password</label><input required type="password" value="password"></div><button class="primary full">Sign in</button></form><div class="hint">Demo mode — any email and password work.</div></div></section></div>`; document.querySelector('#login-form').onsubmit = async (e) => { e.preventDefault(); await api.login(); navigate('dashboard'); render(); }; };
const dashboard = () => { const rows = state.tickets.map((t) => `<div class="ticket-row"><div><div class="ticket-name">${escapeHtml(t.customer_name)}</div><div class="ticket-id">${escapeHtml(t.id)}</div></div><div class="device">${escapeHtml(t.device_info)}</div><span class="status ${t.status}">${statusLabel(t.status)}</span><div class="tech">${t.created_at}</div><button class="icon-btn" data-log="${t.id}">+</button></div>`).join(''); root.innerHTML = `<div class="dashboard">${navigation('tech')}<div class="dash-head"><div><h1>Repair tickets</h1><p>Track every device from check-in to pickup.</p></div><button class="primary" id="new-ticket">+ New ticket</button></div><section class="tickets"><div class="table-head"><span>Customer</span><span>Device</span><span>Status</span><span>Created</span><span></span></div>${rows || '<div class="empty">No tickets yet.</div>'}</section></div>`; document.querySelector('#new-ticket').onclick = newTicket; document.querySelectorAll('[data-log]').forEach((b) => { b.onclick = () => addLog(b.dataset.log); }); };
const newTicket = () => { openModal('New repair ticket', `<form id="ticket-form"><div class="field"><label>Customer name</label><input required name="customer_name"></div><div class="field"><label>Device</label><input required name="device_info"></div><div class="field"><label>Initial status</label><select name="status"><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="waiting_parts">Waiting for parts</option></select></div><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Create ticket</button></div></form>`); document.querySelector('#ticket-form').onsubmit = async (e) => { e.preventDefault(); const ticket = Object.fromEntries(new FormData(e.target)); Object.assign(ticket, { id: `RF-${Math.floor(1000 + Math.random() * 8999)}`, created_at: 'Just now' }); await api.createTicket(ticket); closeModal(); render(); showToast('Ticket created'); }; };
const addLog = (id) => { openModal(`Add progress log · ${id}`, `<form id="log-form"><div class="field"><label>Update for the customer</label><textarea required name="note"></textarea></div><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Save update</button></div></form>`); document.querySelector('#log-form').onsubmit = async (e) => { e.preventDefault(); await api.addLog(id, new FormData(e.target).get('note')); closeModal(); showToast('Progress log saved'); }; };
const lookup = () => { root.innerHTML = `<div class="screen shell">${navigation('customer')}<section class="lookup-wrap"><div class="lookup-card"><div class="brand"><span class="brand-mark">✦</span>FixFlow</div><h1>Check your repair</h1><p>Enter the ticket ID from your repair receipt to see the latest update.</p><form id="lookup-form"><div class="field"><label>Repair ticket ID</label><input required placeholder="e.g. RF-4821"></div><button class="primary full">View repair status</button></form><div class="hint">For this demo, try <b>RF-4821</b>.</div></div></section></div>`; document.querySelector('#lookup-form').onsubmit = (e) => { e.preventDefault(); const t = state.tickets.find(({ id }) => id === e.target.querySelector('input').value.trim().toUpperCase()); if (!t) return showToast('We couldn’t find that ticket ID.'); state.selectedTicket = t; navigate('chat'); render(); }; };
const chat = () => { const t = state.selectedTicket; root.innerHTML = `<div class="chat-layout">${navigation('customer')}<header class="chat-header"><div><div class="chat-title">${escapeHtml(t.device_info)}</div><div class="chat-meta">TICKET ${t.id}</div></div><span class="status ${t.status}">${statusLabel(t.status)}</span></header><section id="messages" class="messages"><div class="message agent">Hi ${escapeHtml(t.customer_name.split(' ')[0])}! Your repair is currently <b>${statusLabel(t.status).toLowerCase()}</b>. What would you like to know?</div></section><form id="chat-form" class="composer"><input required placeholder="Ask about your repair…"><button class="send">Send</button></form></div>`; document.querySelector('#chat-form').onsubmit = async (e) => { e.preventDefault(); const input = e.target.querySelector('input'); const message = input.value.trim(); input.value = ''; document.querySelector('#messages').insertAdjacentHTML('beforeend', `<div class="message customer">${escapeHtml(message)}</div>`); await api.chat(t.id, message); document.querySelector('#messages').insertAdjacentHTML('beforeend', `<div class="message agent">Your repair is ${statusLabel(t.status).toLowerCase()}. Our technician will add another update as soon as there’s more to share.</div>`); }; };
const views = { home, login, dashboard, lookup, chat };
export { render };
